const data_prod = [
            {
                "id": "170207143605005",
                "lastUpdated": "2019-05-08 15:32:32",
                "name": null,
                "shortName": null,
                "longName": null,
                "baseImage": "http://content-house.pro/cs/api/getProductFile?type=images&productId=170207143605005&login=lego&password=e7ddaob3&name=70166_Box1&extension=jpg&customerId=85&compression=50",
                "article": "Конструктор LEGO Agents 70166 Внедрение шпионов",
                "manufacturer": "LEGO",
                "annotation": "<br>Внимание, ультра-агент Трэй Свифт! Шпионы уже вторглись в город в своем механическом Пауке с заданием украсть чип, содержащий сверхсекретные файлы агента. Отрази щитом взрывы от ракет, выпущенных из шипованных сборных шутеров роботов, и стреляй в ответ из собственного мощного шипованного шутера. Между тем, остерегайся роботов-пауков, пытающихся украсть чип для своего злого хозяина — ты должен отбиваться от их атак, защищая секретную информацию ультра-агента. Потом поиграй в другие захватывающие миссии на планшете, используя гаджет приложения Ultra с двумя AppBricks! В набор входят 2 минифигурки с оружием и разнообразным аксессуарами: Шпионы и ультра-агент Трэй Свифт.",
                "categoryIdStr": "01010101",
                "categoryId": 70038,
                "partNumber": "70166",
                "brand": "LEGO",
                "family": null,
                "series": "Agents",
                "model": "Внедрение шпионов",
                "hasImage": true,
                "hasVideo": true,
                "has360View": false,
                "hasInstructions": true,
                "hasMarketText": true,
                "model_color": null,
                "model_union": null,
                "ean": "5702015353847"
            },
            {
                "id": "170207145629439",
                "lastUpdated": "2019-05-08 15:32:34",
                "name": null,
                "shortName": null,
                "longName": null,
                "baseImage": "http://content-house.pro/cs/api/getProductFile?type=images&productId=170207145629439&login=lego&password=e7ddaob3&name=70168_Box1&extension=jpg&customerId=85&compression=50",
                "article": "Конструктор LEGO Agents 70168 Добыча алмазов",
                "manufacturer": "LEGO",
                "annotation": null,
                "categoryIdStr": "01010101",
                "categoryId": 70038,
                "partNumber": "70168",
                "brand": "LEGO",
                "family": null,
                "series": "Agents",
                "model": "Добыча алмазов",
                "hasImage": true,
                "hasVideo": true,
                "has360View": false,
                "hasInstructions": true,
                "hasMarketText": false,
                "model_color": null,
                "model_union": null,
                "ean": "5702015354271"
            },
            {
                "id": "170207154600651",
                "lastUpdated": "2019-05-08 15:32:35",
                "name": null,
                "shortName": null,
                "longName": null,
                "baseImage": "http://content-house.pro/cs/api/getProductFile?type=images&productId=170207154600651&login=lego&password=e7ddaob3&name=70164_Box1&extension=jpg&customerId=85&compression=50",
                "article": "Конструктор LEGO Agents 70164 Штормовое нападение Сайклона",
                "manufacturer": "LEGO",
                "annotation": "<br>Красный код тревоги, ультра агенты! Объединитесь в борьбе против суперзлодея Сайклона, повелителя ветра, который обрушивает разрушающий шторм на Астор Сити. Невероятный трансформирующийся летательный аппарат Сайклона оснащен гигантскими вращающимися роторными лопастями для создания торнадо, лазерными пушками и автоматическими ракетными шутерами. Сложи колеса футуристического мотоцикла агента Кайлы Феникс, чтобы перейти в режим полета, и отстреливайся из двойных шипованных шутеров. Удвой воздушную атаку с агентом Джеком Фьюри, используя его реактивную ранцевую установку и большую плазменную пушку. Но будь осторожен – летательный аппарат Сайклона может быстро трансформироваться в массивного робота, который выглядит как он... только намного больше! Цель этого супер злодея – создать торнадо и засосать все деньги, поэтому поспеши защитить имущество Астор Сити и его горожан! В набор входят 4 минифигурки с разнообразным оружием и аксессуарами: Сайклон, охранник Астор Сити, агент Кайла Феникс и агент Джек Фьюри.",
                "categoryIdStr": "01010101",
                "categoryId": 70038,
                "partNumber": "70164",
                "brand": "LEGO",
                "family": null,
                "series": "Agents",
                "model": "Штормовое нападение Сайклона",
                "hasImage": true,
                "hasVideo": true,
                "has360View": false,
                "hasInstructions": true,
                "hasMarketText": true,
                "model_color": null,
                "model_union": null,
                "ean": "5702015124270"
            },
            {
                "id": "170207144830767",
                "lastUpdated": "2019-05-08 15:32:34",
                "name": null,
                "shortName": null,
                "longName": null,
                "baseImage": "http://content-house.pro/cs/api/getProductFile?type=images&productId=170207144830767&login=lego&password=e7ddaob3&name=70167_Box1&extension=jpg&customerId=85&compression=50",
                "article": "Конструктор LEGO Agents 70167 Похищение золота",
                "manufacturer": "LEGO",
                "annotation": null,
                "categoryIdStr": "01010101",
                "categoryId": 70038,
                "partNumber": "70167",
                "brand": "LEGO",
                "family": null,
                "series": "Agents",
                "model": "Похищение золота",
                "hasImage": true,
                "hasVideo": true,
                "has360View": false,
                "hasInstructions": true,
                "hasMarketText": false,
                "model_color": null,
                "model_union": null,
                "ean": "5702015354257"
            },
            {
                "id": "170207153512294",
                "lastUpdated": "2019-05-08 15:32:35",
                "name": null,
                "shortName": null,
                "longName": null,
                "baseImage": "http://content-house.pro/cs/api/getProductFile?type=images&productId=170207153512294&login=lego&password=e7ddaob3&name=70162_Box1&extension=jpg&customerId=85&compression=50",
                "article": "Конструктор LEGO Agents 70162 Перехват Инферно",
                "manufacturer": "LEGO",
                "annotation": "<br>Вызываю суперагента Соломона Блейза! Высоко над Астор Сити на своем огненном ховерборде парит Инферно. На супер злодее огнеметный костюм и он сбрасывает динамитные шашки, сея страх среди горожан. Отправляйся в погоню на великолепном автомобиле с откидным верхом агента Соломона, оснащенном огромными колесами и защитными полупрозрачными голубыми энергетическими панелями. Сложи колеса так, чтобы перейти в режим полета, и начни воздушную битву! Нацель на огненного преступника двойные лазерные пушки и спрятанные автоматические ракетные шутеры. Если ты поймешь, что больше не можешь отбивать атаки, активируй супер классную функцию катапультирования кресла, чтобы спастись от смертоносного огня! В набор входят 2 минифигурки с разнообразным оружием и аксессуарами: Инферно и агент Соломон Блейз!",
                "categoryIdStr": "01010101",
                "categoryId": 70038,
                "partNumber": "70162",
                "brand": "LEGO",
                "family": null,
                "series": "Agents",
                "model": "Перехват Инферно",
                "hasImage": true,
                "hasVideo": true,
                "has360View": false,
                "hasInstructions": true,
                "hasMarketText": true,
                "model_color": null,
                "model_union": null,
                "ean": "5702015124256"
            },
            {
                "id": "170207161348768",
                "lastUpdated": "2019-05-08 15:32:36",
                "name": null,
                "shortName": null,
                "longName": null,
                "baseImage": "http://content-house.pro/cs/api/getProductFile?type=images&productId=170207161348768&login=lego&password=e7ddaob3&name=70161_Box1&extension=jpg&customerId=85&compression=50",
                "article": "Конструктор LEGO Agents 70161 Вторжение Тремора",
                "manufacturer": "LEGO",
                "annotation": "<br>Внимание, суперагент Джек Фьюри! Тремор, супер злодей с железными кулаками, крушит все вокруг на улицах Астор Сити на своем устрашающем бронированном танке. Твоя задача – защитить ультра чип, ведь на нем хранятся все секретные планы суперагентов. Держись подальше от массивных опасных кулаков машины. Отражай маневренные ракеты щитом и стреляй шипами из шутера. Используй все свои навыки, чтобы перехитрить этого бронированного суперзлодея. Всего один сильный удар машины Тремора способен разрушить центральную базу данных и тогда он получит доступ к ценному ультра чипу! В набор входят 2 минифигурки с разнообразным оружием и аксессуарами: Тремор и агент Джек Фьюри.",
                "categoryIdStr": "01010101",
                "categoryId": 70038,
                "partNumber": "70161",
                "brand": "LEGO",
                "family": null,
                "series": "Agents",
                "model": "Вторжение Тремора",
                "hasImage": true,
                "hasVideo": true,
                "has360View": false,
                "hasInstructions": true,
                "hasMarketText": true,
                "model_color": null,
                "model_union": null,
                "ean": "5702015124249"
            },
            {
                "id": "170207162413984",
                "lastUpdated": "2019-05-08 15:32:37",
                "name": null,
                "shortName": null,
                "longName": null,
                "baseImage": "http://content-house.pro/cs/api/getProductFile?type=images&productId=170207162413984&login=lego&password=e7ddaob3&name=70163_Box1&extension=jpg&customerId=85&compression=50",
                "article": "Конструктор LEGO Agents 70163 Токсическая атака Токсикиты",
                "manufacturer": "LEGO",
                "annotation": "<br>Явиться на службу, суперагент Куртис Болт! Злобная Токсикита смогла обнаружить суперсекретную лабораторию на острове Поинтер и сбрасывает токсичные бомбы с вертолета, пилотируемого ее приспешником Ретоксом. В лаборатории ученый Астор Сити проводит жизненно важные эксперименты с использованием защитных когтей дистанционного управления. Поспеши к нему на помощь и защити кристалл, который Токсикита пытается украсть для подпитки своего супероружия – если оно попадет не в те руки, могут быть ужасные последствия, даже полное разрушение города! Стреляй из шипованного шутера и выпускай маневренные ракеты из лаборатории, когда Токсикита начнет спускаться с вертолета по цепи. Перехвати ее, прежде чем она взорвет лабораторию и получит доступ к кристаллу, который полностью растопит метрополис! В набор входят 4 минифигурки с разнообразным оружием и аксессуарами: Токсикита, Ретокс, агент Куртис Болт и ученый Астор Сити.",
                "categoryIdStr": "01010101",
                "categoryId": 70038,
                "partNumber": "70163",
                "brand": "LEGO",
                "family": null,
                "series": "Agents",
                "model": "Токсическая атака Токсикиты",
                "hasImage": true,
                "hasVideo": true,
                "has360View": false,
                "hasInstructions": true,
                "hasMarketText": true,
                "model_color": null,
                "model_union": null,
                "ean": "5702015124263"
            },
            {
                "id": "170207142906129",
                "lastUpdated": "2019-05-08 15:32:32",
                "name": null,
                "shortName": null,
                "longName": null,
                "baseImage": "http://content-house.pro/cs/api/getProductFile?type=images&productId=170207142906129&login=lego&password=e7ddaob3&name=70160_Box1&extension=jpg&customerId=85&compression=50",
                "article": "Конструктор LEGO Agents 70160 Прибрежный рейд",
                "manufacturer": "LEGO",
                "annotation": "<br>Срочный звонок от новобранца, суперагента Макса Бернса! Адам Эсид пытается украсть ящики с токсичными веществами с пристани Астор Сити по указу своего хозяина, суперзлодея Токсикиты. Начни погоню на великолепном квадроцикле и реактивном скутере 2-в-1 и останови этот прибрежный набег! Разгони автомобиль до невероятных скоростей и стреляй из заряженных шипами шутеров прямо на ходу, а чтобы прицелиться было удобнее, отсоедини их и используй в качестве ручного оружия. Активируй функцию реактивного скутера, чтобы разделиться и продолжить водную погоню. Прикрепи заднюю лебедку, чтобы притянуть скоростной скутер, а когда найдешь пропавшие ящики, используй ее, чтобы перенести их в безопасное место. В набор входят 2 минифигурки с оружием: агент Макс Бернс и Адам Эсид.",
                "categoryIdStr": "01010101",
                "categoryId": 70038,
                "partNumber": "70160",
                "brand": "LEGO",
                "family": null,
                "series": "Agents",
                "model": "Прибрежный рейд",
                "hasImage": true,
                "hasVideo": true,
                "has360View": false,
                "hasInstructions": true,
                "hasMarketText": true,
                "model_color": null,
                "model_union": null,
                "ean": "5702015124232"
            },
            {
                "id": "170207151011630",
                "lastUpdated": "2019-05-08 15:32:35",
                "name": null,
                "shortName": null,
                "longName": null,
                "baseImage": "http://content-house.pro/cs/api/getProductFile?type=images&productId=170207151011630&login=lego&password=e7ddaob3&name=70169_Box1&extension=jpg&customerId=85&compression=50",
                "article": "Конструктор LEGO Agents 70169 Секретный патруль агентов",
                "manufacturer": "LEGO",
                "annotation": null,
                "categoryIdStr": "01010101",
                "categoryId": 70038,
                "partNumber": "70169",
                "brand": "LEGO",
                "family": null,
                "series": "Agents",
                "model": "Секретный патруль агентов",
                "hasImage": true,
                "hasVideo": true,
                "has360View": false,
                "hasInstructions": true,
                "hasMarketText": false,
                "model_color": null,
                "model_union": null,
                "ean": "5702015353854"
            },
            {
                "id": "170207152330642",
                "lastUpdated": "2019-05-08 15:32:35",
                "name": null,
                "shortName": null,
                "longName": null,
                "baseImage": "http://content-house.pro/cs/api/getProductFile?type=images&productId=170207152330642&login=lego&password=e7ddaob3&name=70170_Box1&extension=jpg&customerId=85&compression=50",
                "article": "Конструктор LEGO Agents 70170 Воздушное сражение",
                "manufacturer": "LEGO",
                "annotation": null,
                "categoryIdStr": "01010101",
                "categoryId": 70038,
                "partNumber": "70170",
                "brand": "LEGO",
                "family": null,
                "series": "Agents",
                "model": "Воздушное сражение",
                "hasImage": true,
                "hasVideo": true,
                "has360View": false,
                "hasInstructions": true,
                "hasMarketText": false,
                "model_color": null,
                "model_union": null,
                "ean": "5702015354202"
            },
            {
                "id": "170207155749159",
                "lastUpdated": "2019-05-08 15:32:36",
                "name": null,
                "shortName": null,
                "longName": null,
                "baseImage": "http://content-house.pro/cs/api/getProductFile?type=images&productId=170207155749159&login=lego&password=e7ddaob3&name=70165_Box1&extension=jpg&customerId=85&compression=50",
                "article": "Конструктор LEGO Agents 70165 Штаб-квартира Суперагентов",
                "manufacturer": "LEGO",
                "annotation": "<br>Чрезвычайное происшествие! Злобный кибернетический хакер Терабайт напал на передвижную штаб-квартиру суперагентов и хочет вывести из строя всю коммуникационную сеть Астор Сити. Садись за руль замаскированного высокотехнологичного грузовика и стреляй из автоматических ракетных шутеров, чтобы прогнать его. Запускай спрятанный летательный аппарат, чтобы шпионить за врагами и собирать информацию с воздуха. Нажми на рычаг, чтобы отсоединить водительскую кабину, открыть задний отсек грузовика и получить доступ к великолепной штаб-квартире. Подключи ноутбук с суперсекретными планами агентов в комнате совещаний и просмотри их на экране. Проанализируй данные и выполни испытания и опыты в лаборатории вместе с профессором Кристиной Хайдрон. Прикрепи реактивный ранец и выдвижную роботизированную руку, чтобы подготовить агента Феникс к взлету. Не дай Терабайту убежать с ноутбуком, на котором сохранены все секретные файлы суперагентов, пока его высокотехнологичный робот пытается разрушить всю коммуникационную систему, сбрасывая бомбы на спутниковые тарелки. Съезжай на багги по рампе и стреляй шипами из шутеров, чтобы защитить штаб-квартиру суперагентов. Ты должен заточить этого преступного фанатика компьютеров в высокотехнологичную тюремную камеру до того, как он причинит еще больший ущерб! В набор входят 5 минифигурок с аксессуарами: Терабайт, агент Соломон Блейз, агент Кайла Феникс, агент Куртис Болт и профессор Кристина Хайдрон.",
                "categoryIdStr": "01010101",
                "categoryId": 70038,
                "partNumber": "70165",
                "brand": "LEGO",
                "family": null,
                "series": "Agents",
                "model": "Штаб-квартира Суперагентов",
                "hasImage": true,
                "hasVideo": true,
                "has360View": false,
                "hasInstructions": true,
                "hasMarketText": true,
                "model_color": null,
                "model_union": null,
                "ean": "5702015124287"
            }
]
export default data_prod